CREATE TABLE employee (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE ingredient (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  employee_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (employee_id) REFERENCES employee(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE salad (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  employee_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (employee_id) REFERENCES employee(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE compose (
  ingredient_id INT UNSIGNED NOT NULL,
  salad_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (salad_id) REFERENCES salad(id),
  FOREIGN KEY (ingredient_id) REFERENCES ingredient(id)
);

CREATE TABLE order_table (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE belongs (
  salad_id INT UNSIGNED NOT NULL,
  order_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (salad_id) REFERENCES salad(id),
  FOREIGN KEY (order_id) REFERENCES order_table(id)
);

INSERT INTO employee (id, email, password)
VALUES
  (1, "jdoe@mail.com", "123456");
